fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: klub@orletalukow.pl
    sender_name: Orlęta Łuków
  registration:
    confirmation:
      enabled: true
  resetting:
    email:
      from_email:
        address:        klub@orletalukow.pl
        sender_name:    Orlęta Łuków