fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  service:
    mailer: fos_user.mailer.twig_swift
  from_email:
    address:        noreply@orletalukow.pl
    sender_name:    Orlęta Łuków
  registration:
    confirmation:
      enabled: true
      from_email:
        address:        noreply@orletalukow.pl
        sender_name:    Orlęta Łuków
      template:   'registration/email.txt.twig'
  resetting:
    email:
      from_email:
        address:        noreply@orletalukow.pl
        sender_name:    Orlęta Łuków