sonata_admin:
    title: 'Orlęta Łuków'
    title_logo: /images/orleta_logo.png
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

