version: "3.1"
services:
    webserver:
      environment:
        TZ: "Europe/Warsaw"
      image: nginx:alpine
      container_name: docker-symfony4-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./phpdocker/orleta.crt:/etc/nginx/ssl/orleta.crt
          - ./phpdocker/orleta.key:/etc/nginx/ssl/orleta.key
          - ./phpdocker/certificate_sz.key:/etc/nginx/ssl/certificate_sz.key
          - ./phpdocker/private_sz.key:/etc/nginx/ssl/private_sz.key
      ports:
       - "80:80"
       - "443:443"

    php-fpm:
      environment:
        TZ: "Europe/Warsaw"
      image: php-fpm:7.4
      build: phpdocker/php-fpm
      container_name: docker-symfony4-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

