<?php

namespace App\DataFixtures;

use App\Entity\Match;
use App\Entity\PageType;
use App\Entity\Queue;
use App\Entity\Season;
use App\Entity\Table;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;
use DateTime;

class AppFixtures extends Fixture
{

    /**
     * @param ObjectManager $manager
     */
    private $manager;

    public function load(ObjectManager $manager)
    {
        $this->manager = $manager;

        $season = $this->season();
        $manager->persist($season);
        $manager->flush();
        $this->table($season, $manager);
        $manager->flush();
        $this->queue($season, $manager);
        $manager->flush();
        $this->pageType($manager);
        $manager->flush();
    }

    /**
     * @param ObjectManager $manager
     */
    private function pageType($manager) {
        $pageTypes = ['news', 'page'];

        foreach ($pageTypes as $pageType) {
            $newPageType = new PageType();
            $newPageType->setType($pageType);
            $manager->persist($newPageType);
        }
    }

    private function season(): Season
    {
        return (new Season())
            ->setSeason('2019/2020')
            ->setCurrent(1);
    }

    private function queue(Season $season, ObjectManager $manager)
    {
        for ($queueNumber = 1; $queueNumber < 9; $queueNumber++) {
            $queue = (new Queue())
                ->setSeason($season)
                ->setNumber($queueNumber)
                ->setTimeStart(new DateTime())
                ->setTimeEnd(new DateTime());
            $manager->persist($queue);
            $this->match($queue, $manager);
        }
    }

    private function match(Queue $queue, ObjectManager $manager): void
    {
        $matches = [
            1 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 1,
                    'winner' => 11,
                    'home' => 3,
                    'away' => 11,
                    'scoreHome' => 0,
                    'scoreAway' => 3,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 12,
                    'away' => 13,
                    'scoreHome' => 1,
                    'scoreAway' => 1,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 2,
                    'goalsAway' => 1,
                    'winner' => 9,
                    'home' => 9,
                    'away' => 2,
                    'scoreHome' => 3,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 4,
                    'winner' => 6,
                    'home' => 16,
                    'away' => 6,
                    'scoreHome' => 0,
                    'scoreAway' => 3,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 2,
                    'goalsAway' => 1,
                    'winner' => 10,
                    'home' => 10,
                    'away' => 14,
                    'scoreHome' => 3,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 4,
                    'goalsAway' => 2,
                    'winner' => 1,
                    'home' => 1,
                    'away' => 5,
                    'scoreHome' => 3,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 1,
                    'goalsAway' => 3,
                    'winner' => 7,
                    'home' => 4,
                    'away' => 7,
                    'scoreHome' => 0,
                    'scoreAway' => 3,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 3,
                    'goalsAway' => 1,
                    'winner' => 8,
                    'home' => 8,
                    'away' => 15,
                    'scoreHome' => 3,
                    'scoreAway' => 0,
                ],
            ],
            2 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 11,
                    'away' => 7,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 5,
                    'away' => 4,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 14,
                    'away' => 1,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 6,
                    'away' => 10,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 2,
                    'away' => 16,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 13,
                    'away' => 9,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 8,
                    'away' => 12,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 3,
                    'away' => 15,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            3 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 15,
                    'away' => 11,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 12,
                    'away' => 3,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 9,
                    'away' => 8,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 16,
                    'away' => 13,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 10,
                    'away' => 2,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 1,
                    'away' => 6,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 4,
                    'away' => 14,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 7,
                    'away' => 5,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            4 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 11,
                    'away' => 5,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 14,
                    'away' => 7,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 6,
                    'away' => 4,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 2,
                    'away' => 1,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 13,
                    'away' => 10,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 8,
                    'away' => 16,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 3,
                    'away' => 9,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 15,
                    'away' => 12,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            5 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 12,
                    'away' => 11,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 9,
                    'away' => 15,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 16,
                    'away' => 3,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 10,
                    'away' => 8,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 1,
                    'away' => 13,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 4,
                    'away' => 2,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 7,
                    'away' => 6,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 5,
                    'away' => 14,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            6 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 11,
                    'away' => 14,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 6,
                    'away' => 14,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 2,
                    'away' => 7,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 13,
                    'away' => 4,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 8,
                    'away' => 1,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 3,
                    'away' => 10,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 15,
                    'away' => 16,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 12,
                    'away' => 9,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            7 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 9,
                    'away' => 11,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 16,
                    'away' => 12,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 10,
                    'away' => 15,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 1,
                    'away' => 3,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 4,
                    'away' => 8,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 7,
                    'away' => 13,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 5,
                    'away' => 2,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 14,
                    'away' => 6,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            8 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 11,
                    'away' => 6,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 2,
                    'away' => 14,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 10,
                    'away' => 5,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 8,
                    'away' => 7,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 3,
                    'away' => 4,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 15,
                    'away' => 1,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 12,
                    'away' => 10,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 9,
                    'away' => 16,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            9 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            10 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            11 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            12 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            13 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            14 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            15 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            16 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            17 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            18 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            19 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            20 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            21 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            22 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            23 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            24 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            25 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            26 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            27 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            28 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            29 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],
            30 => [
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
                [
                    'queue' => $queue,
                    'goalsHome' => 0,
                    'goalsAway' => 0,
                    'winner' => null,
                    'home' => 0,
                    'away' => 0,
                    'scoreHome' => 0,
                    'scoreAway' => 0,
                ],
            ],

        ];

        foreach ($matches[$queue->getNumber()] as $leagueQueue) {
            $match = (new Match())
                ->setQueue($queue)
                ->setHome($manager->getRepository(Table::class)->find($leagueQueue['home']))
                ->setAway($manager->getRepository(Table::class)->find($leagueQueue['away']))
                ->setGoalsHome($leagueQueue['goalsHome'])
                ->setGoalsAway($leagueQueue['goalsAway'])
                ->setWinner(
                    $leagueQueue['winner'] === null ? null : $manager->getRepository(Table::class)->find($leagueQueue['winner'])
                )
                ->setScoreHome($leagueQueue['scoreHome'])
                ->setScoreAway($leagueQueue['scoreAway']);

            $manager->persist($match);
        }
    }

    private function table(Season $season, ObjectManager $manager): void
    {
        $teams = [
            'Orlęta Łuków',
            'Kłos Chełm',
            'Łada 1945 Biłgoraj',
            'Huczwa Tyszowce',
            'Włodawianka Włodowa',
            'Huragan Międzyrzec Podlaski',
            'Lewart Lubartów',
            'Granit Bychawa',
            'Tomasovia Tomaszów Lubelski',
            'Powiślak Końskowola',
            'Victoria Zmudź',
            'Lublinianka Lublin',
            'Kryształ Werbkowice',
            'Sparta Rejowiec Fabryczny',
            'Górnik II Łęczna',
            'Unia Hrubieszów',
        ];

        foreach ($teams as $team) {
            $newTeam = (new Table())
                ->setSeason($season)
                ->setClub($team)
                ->setMatches(0)
                ->setDifferenceGoals(0)
                ->setDraws(0)
                ->setLost(0)
                ->setWins(0)
                ->setPlace(0)
                ->setPoints(0)
                ->setScoredGoals(0)
                ->setLostGoals(0);

            $manager->persist($newTeam);
        }
    }
}
